/**:
  ros__parameters:
    # control parameters
    "output_dir": "/tmp"
    "input_dir": ""

    # test suite parameters
    "test_name": "random_test"
    "map_name": "kashiwanoha_map"
    "npc_count": 5
    "test_count": 1
    "npc_min_spawn_distance_from_ego": 30.0
    "npc_max_spawn_distance_from_ego": 200.0
    "min_green_light_duration" : 20.0
    "max_green_light_duration" : 20.0
