/**:
  ros__parameters:
    # control parameters
    "output_dir": "/home/pzyskowski/projects/tier/deliverable/2024_Q4/WP9-bt/scenarios/5_npcs_right_of_way_2"
    "input_dir": ""

    # test suite parameters
    "test_name": "random_test"
    "test_count": 50
    "map_name": "shinjuku_map"
    "ego_goal_lanelet_id": 131 # -1 means full goal randomization
    "ego_goal_s": 0.0
    "npc_count" : 5
    "test_timeout" : 10.0
    "npc_max_spawn_distance_from_ego" : 40.0
    "npc_min_spawn_distance_from_ego" : 10.0
    "npc_min_speed" : 2.0
    "npc_max_speed" : 5.0


